name: LinFood
description: A /give plugin for food only
version: 1.0

author: jacklin213
main: me.jacklin213.linfood.LinFood

commands:
  LinFood:
    description: Lists the basic info
    aliases: lf
    
permissions:
  linfood.*:
    description: Allows all usage of LinFood commands.
    default: op
    children:
      linfood.help: true
      linfood.give: true
  linfood.give.*:
    description: Allows all /lf give commands
    default: op
    children:
      linfood.give: true
      linfood.give.list: true
  linfood.give: 
    description: Allows the /lf give for oneself and others
    default: op
  linfood.give.list:
    description: Allows the listing of all foods.
  linfood.help:
    description: Allows the usage of the help command
    default: op
